FROM 42wim/matterbridge:1.26

RUN apk add --no-cache bash curl git make gcc g++ python3 nodejs npm

WORKDIR /opt/app/
COPY package*.json ./
RUN npm install
COPY . .

COPY ./matterbridge.toml /etc/matterbridge/matterbridge.toml

# Keep container running and interactive
# ENTRYPOINT ["/bin/sh"]
# CMD ["-c", "tail -f /dev/null"]
ENTRYPOINT ["npm"]

# EXPOSE 6369
CMD ["run", "bridge"]
