FROM 42wim/matterbridge:1.26

RUN apk add --no-cache bash curl git make gcc g++ python3 nodejs npm

WORKDIR /opt/app/
COPY package*.json ./
RUN npm install
COPY . .

# EXPOSE 6369

ENTRYPOINT ["npm"]
CMD ["run", "bridge"]
