[general]
RemoteNickFormat = "[{PROTOCOL}] <{NICK}> "

[xmpp.matterbridge]
Server="selfdev-prosody.dev.local"
Muc="conference.selfdev-prosody.dev.local"
Jid="matterbridge@selfdev-prosody.dev.local"
Password="mAtter_BRiDGE-123"
Nick="matterbridge"
SkipTLSVerify=true
# NoTLS=true

[xmpp.matter]
Server="selfdev-prosody.dev.local"
Muc="conference.selfdev-prosody.dev.local"
Jid="matter@selfdev-prosody.dev.local"
Password="123"
Nick="matter"
SkipTLSVerify=true
# NoTLS=true

[telegram.astr_angel_bot]
Token="7720071997:AAGc75WMud54G7q29gwuwOorpayDL_f9PzA"  # astr_angel_bot: t.me/astr_angel_bot
RemoteNickFormat="<{NICK}> " # How your message will be formatted when bridged.
MessageFormat="HTMLNick :"
QuoteFormat="{MESSAGE} (re @{QUOTENICK}: {QUOTEMESSAGE})"
QuoteLengthLimit=46 # Truncuate long quotes to prevent spammy bridged messages
IgnoreMessages="^/" # Don't bridge bot commands

[telegram.az1_ai_bot]
Token="7672478424:AAF9EzIYf4dEuzwE_Y56BFgAmhHX81EwjU8"  # az1_ai_bot: t.me/az1_ai_bot
RemoteNickFormat="<{NICK}> " # How your message will be formatted when bridged.
MessageFormat="HTMLNick :"
QuoteFormat="{MESSAGE} (re @{QUOTENICK}: {QUOTEMESSAGE})"
QuoteLengthLimit=46 # Truncuate long quotes to prevent spammy bridged messages
IgnoreMessages="^/" # Don't bridge bot commands (as the responses will not be bridged)

[discord.selfdev_bot]
Token="MTM1MDk1MzA3NTkyNTU4NTk2MA.GGyAf_.z49SNbYC8M28vxbUelf-nvJIOxogG-RkwLQS8g"
Server="az1"

[[gateway]]
name="xmpp-telegram"
enable=true

# How to get channel
# https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L1855

  [[gateway.inout]]
  account="xmpp.matterbridge"
  channel="bridge"  # NOTE: matterbridge can only join the room name (without @domain.com)

  [[gateway.inout]]
  account="xmpp.matter"
  channel="bridge@conference.selfdev-prosody.dev.local"  # NOTE: is needed to create a room on xmpp server

  # [[gateway.inout]]
  # account="telegram.az1_ai_bot"
  # channel="-1002452967040"  # @az1_channel: t.me/az1_channel
  # # The channel is retrieved from the matterbridge logs (see Channel):
  # #     ime="2025-03-16T20:23:05Z" level=debug msg="<= Message is config.Message{Text:"1", Channel:"-1002452967040", Username:"az1_channel", UserID:"-1002452967040", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), ID:"18", Extra:map[string][]interface {}{}}" func=handleRecv file="bridge/telegram/handlers.go:238" prefix=telegram

  [[gateway.inout]]
  account="telegram.az1_ai_bot"
  channel="1426287173"  # @az1_ai_bot: t.me/az1_ai_bot
  # The channel is retrieved from the matterbridge logs (see Channel):
  #     time="2025-03-16T20:23:39Z" level=debug msg="<= Message is config.Message{Text:"2", Channel:"1426287173", Username:"artemarakcheev", UserID:"1426287173", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), ID:"382", Extra:map[string][]interface {}{}}" func=handleRecv file="bridge/telegram/handlers.go:238" prefix=telegram

  [[gateway.inout]]
  account="discord.selfdev_bot"
  channel="general"

